Return-Path: <ksummit+bounces-150-lists=lfdr.de@lists.linux.dev>
X-Original-To: lists@lfdr.de
Delivered-To: lists@lfdr.de
Received: from ewr.edge.kernel.org (ewr.edge.kernel.org [147.75.197.195])
	by mail.lfdr.de (Postfix) with ESMTPS id CBDF03690BF
	for <lists@lfdr.de>; Fri, 23 Apr 2021 13:01:57 +0200 (CEST)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by ewr.edge.kernel.org (Postfix) with ESMTPS id 68A1B1C7EB7
	for <lists@lfdr.de>; Fri, 23 Apr 2021 11:01:55 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 34EC32FA6;
	Fri, 23 Apr 2021 11:01:48 +0000 (UTC)
X-Original-To: ksummit@lists.linux.dev
Received: from mx2.suse.de (mx2.suse.de [195.135.220.15])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 1EB4E72;
	Fri, 23 Apr 2021 11:01:47 +0000 (UTC)
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.221.27])
	by mx2.suse.de (Postfix) with ESMTP id 8DCE8B114;
	Fri, 23 Apr 2021 11:01:45 +0000 (UTC)
Date: Fri, 23 Apr 2021 13:01:45 +0200
Message-ID: <s5htunx5ko6.wl-tiwai@suse.de>
From: Takashi Iwai <tiwai@suse.de>
To: Thorsten Leemhuis <linux@leemhuis.info>
Cc: Greg KH <gregkh@linuxfoundation.org>,
	Linus Torvalds <torvalds@linux-foundation.org>,
	"Rafael J. Wysocki" <rafael@kernel.org>,
	regressions@lists.linux.dev,
	Linux Kernel Mailing List <linux-kernel@vger.kernel.org>,
	Konstantin Ryabitsev <konstantin@linuxfoundation.org>,
	Pablo Neira Ayuso <pablo@netfilter.org>,
	ksummit@lists.linux.dev,
	workflows@vger.kernel.org
Subject: Re: RFC: building a regression tracking bot for Linux kernel development
In-Reply-To: <8a44e6b3-fff4-ea6f-2643-bb2a15ff990a@leemhuis.info>
References: <268a3049-7c0b-8a33-1ff6-5a2d35fcba16@leemhuis.info>
	<YIKdQKJNZOSfdL9B@kroah.com>
	<8a44e6b3-fff4-ea6f-2643-bb2a15ff990a@leemhuis.info>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
X-Mailing-List: ksummit@lists.linux.dev
List-Id: <ksummit.lists.linux.dev>
List-Subscribe: <mailto:ksummit+subscribe@lists.linux.dev>
List-Unsubscribe: <mailto:ksummit+unsubscribe@lists.linux.dev>
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII

On Fri, 23 Apr 2021 12:49:25 +0200,
Thorsten Leemhuis wrote:
> 
> On 23.04.21 12:11, Greg KH wrote:
> > On Thu, Apr 22, 2021 at 09:16:40AM +0200, Thorsten Leemhuis wrote:
> >> That can't be all
> >> -----------------
> >>
> >> Of course the world is more complicated than the simple example scenario
> >> above, as the devil is always in the details. The three most obvious
> >> problems the initial ideal scenario left aside:
> >>
> >> * The reporter doesn't specify the #regzb tag at all. Regzbot can't do
> >> anything about it, it sadly won't have visionary power and a AI engine
> >> any time soon. Some human (for a while that often will be me) thus needs
> >> to reply with the tag with a proper reply-to to the report to make
> >> regboz track it.
> > 
> > Any specific format/tag we can use to help make this easier?  Or is that
> > just something that you are going to do "by hand" to start with?
> 
> For now making sure regressions@lists.linux.dev is added to the CCed of
> any replies to regression reports would be a really big help to already
> establish it as central place where they are all visible. Then no human
> or bot needs to monitor hundreds of mailing list to find them -- which
> obviously is doomed to fail and was one of the pain points when I
> tracked regressions manually years ago.

That sounds great.

One thing I still wonder is how to populate the report from distro bug
trackers.  AFAIK, many reports come from there directly or
indirectly.

Can regzbot can have a reference to bug trackers or such?


thanks,

Takashi

